<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Acceso extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Acceso_model');
    } 

    /*
     * Listing of acceso
     */
    function index()
    {
        //$data['acceso'] = $this->Acceso_model->get_all_acceso_fecha();
        
        $data['_view'] = 'acceso/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new acceso
     */
    function nuevo()
    {
        if ($this->input->is_ajax_request()) {
        $codigo = $this->input->post('codigo');
        //$hoy = date();
        $sql = "SELECT c.cliente_id FROM cliente c WHERE c.cliente_codigo=".$codigo ;
        $cliente=$this->db->query($sql)->row_array();
        $sql1 = "SELECT inscripcion_id FROM inscripcion WHERE cliente_id=".$cliente['cliente_id']." and date(inscripcion_fechaini) <= date(now()) and date(inscripcion_fechafin) >= date(now()) ";
        $inscripcion=$this->db->query($sql1)->row_array();
        //$acceso = "SELECT * FROM acceso WHERE inscripcion_id=".$inscripcion['inscripcion_id']." and acceso_ingreso=date(now()) ";
        $params = array(
                'cliente_id' => $cliente['cliente_id'],
                'inscripcion_id' => $inscripcion['inscripcion_id'],
                'acceso_estado' => 'INGRESO',
                //'acceso_ingreso' => $this->input->post('acceso_ingreso'),
                //'acceso_salida' => $this->input->post('acceso_salida'),
            );
            
            $acceso_id = $this->Acceso_model->add_acceso($params);
            echo json_encode($inscripcion);
           // redirect('acceso/index');
            }
    }

    function buscarfecha()
    {
         

        if ($this->input->is_ajax_request()) {
            
            $filtro = $this->input->post('filtro');
            //$estado = $this->input->post('estado');
          
            $result = $this->Acceso_model->fechaingreso($filtro);            
      
           echo json_encode($result);
         }     
    }
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'cliente_id' => $this->input->post('cliente_id'),
				'inscripcion_id' => $this->input->post('inscripcion_id'),
				'acceso_estado' => $this->input->post('acceso_estado'),
				'acceso_ingreso' => $this->input->post('acceso_ingreso'),
				'acceso_salida' => $this->input->post('acceso_salida'),
            );
            
            $acceso_id = $this->Acceso_model->add_acceso($params);
            redirect('acceso/index');
        }
        else
        {            
            $data['_view'] = 'acceso/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a acceso
     */
    function edit($acceso_id)
    {   
        // check if the acceso exists before trying to edit it
        $data['acceso'] = $this->Acceso_model->get_acceso($acceso_id);
        
        if(isset($data['acceso']['acceso_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'cliente_id' => $this->input->post('cliente_id'),
					'inscripcion_id' => $this->input->post('inscripcion_id'),
					'acceso_estado' => $this->input->post('acceso_estado'),
					'acceso_ingreso' => $this->input->post('acceso_ingreso'),
					'acceso_salida' => $this->input->post('acceso_salida'),
                );

                $this->Acceso_model->update_acceso($acceso_id,$params);            
                redirect('acceso/index');
            }
            else
            {
                $data['_view'] = 'acceso/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The acceso you are trying to edit does not exist.');
    } 

    /*
     * Deleting acceso
     */
    function remove($acceso_id)
    {
        $acceso = $this->Acceso_model->get_acceso($acceso_id);

        // check if the acceso exists before trying to delete it
        if(isset($acceso['acceso_id']))
        {
            $this->Acceso_model->delete_acceso($acceso_id);
            redirect('acceso/index');
        }
        else
            show_error('The acceso you are trying to delete does not exist.');
    }
    
}
