<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Categoria_proveedor extends CI_Controller{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        $this->load->model('Categoria_proveedor_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }
    /* *****Funcion que verifica el acceso al sistema**** */
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }
    /*
     * Listing of categoria_proveedor
     */
    function index()
    {
        if($this->acceso(114)){
            $data['page_title'] = "Categoria Proveedor";
            $params['limit'] = RECORDS_PER_PAGE; 
            $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

            $config = $this->config->item('pagination');
            $config['base_url'] = site_url('categoria_proveedor/index?');
            $config['total_rows'] = $this->Categoria_proveedor_model->get_all_categoria_proveedor_count();
            $this->pagination->initialize($config);
            
            $data['categoria_proveedor'] = $this->Categoria_proveedor_model->get_all_categoria_proveedor($params);

            $data['_view'] = 'categoria_proveedor/index';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Adding a new categoria_proveedor
     */
    function add()
    {   
        if($this->acceso(114)){
            $data['page_title'] = "Categoria Proveedor";
            $this->load->library('form_validation');

            //$this->form_validation->set_rules('categoriaprov_descripcion','Descripcion es requerida','trim|required|alpha', array('required' => 'Este Campo no debe ser vacio', 'alpha' => 'Solo valores alfanumericos'));
            $this->form_validation->set_rules('categoriaprov_descripcion','Descripcion es requerida','trim|required', array('required' => 'Este Campo no debe ser vacio'));
		
            if($this->form_validation->run())     
            {
                $params = array(
                                    'categoriaprov_descripcion' => $this->input->post('categoriaprov_descripcion'),
                                    'categoriaprov_numero' => 0,
                                   
                );

                $categoria_proveedor_id = $this->Categoria_proveedor_model->add_categoria_proveedor($params);
                redirect('categoria_proveedor/index');
            }
            else
            {
                $data['_view'] = 'categoria_proveedor/add';
                $this->load->view('layouts/main',$data);
            }
        }
    }  

    /*
     * Editing a categoria_proveedor
     */
    function edit($categoriaprov_id)
    {   
        if($this->acceso(114)){
            $data['page_title'] = "Categoria Proveedor";
            // check if the categoria_proveedor exists before trying to edit it
            $data['categoria_proveedor'] = $this->Categoria_proveedor_model->get_categoria_proveedor($categoriaprov_id);

            if(isset($data['categoria_proveedor']['categoriaprov_id']))
            {
                $this->load->library('form_validation');
                            $this->form_validation->set_rules('categoriaprov_descripcion','Descripcion es requerida','trim|required', array('required' => 'Este Campo no debe ser vacio'));
                           

                            if($this->form_validation->run())     
                {   
                    $params = array(
                                            'categoriaprov_descripcion' => $this->input->post('categoriaprov_descripcion'),
                                            
                    );

                    $this->Categoria_proveedor_model->update_categoria_proveedor($categoriaprov_id,$params);            
                    redirect('categoria_proveedor/index');
                }
                else
                {
                    $data['_view'] = 'categoria_proveedor/edit';
                    $this->load->view('layouts/main',$data);
                }
            }
            else
                show_error('The categoria_proveedor you are trying to edit does not exist.');
        }
    } 

    /*
     * Deleting categoria_proveedor
     */
    function remove($categoriaprov_id)
    {
        if($this->acceso(114)){
            $categoria_proveedor = $this->Categoria_proveedor_model->get_categoria_proveedor($categoriaprov_id);

            // check if the categoria_proveedor exists before trying to delete it
            if(isset($categoria_proveedor['categoriaprov_id']))
            {
                $this->Categoria_proveedor_model->delete_categoria_proveedor($categoriaprov_id);
                redirect('categoria_proveedor/index');
            }
            else
                show_error('The categoria_proveedor you are trying to delete does not exist.');
        }
    }

    
}
