<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Contrato extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Contrato_model');
    } 

    /*
     * Listing of contrato
     */
    function index()
    {
        $data['contrato'] = $this->Contrato_model->get_all_contrato();
        
        $data['_view'] = 'contrato/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new contrato
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'estado_id' => $this->input->post('estado_id'),
				'personal_id' => $this->input->post('personal_id'),
				'contrato_cargo' => $this->input->post('contrato_cargo'),
				'contrato_fechaing' => $this->input->post('contrato_fechaing'),
				'contrato_sueldo' => $this->input->post('contrato_sueldo'),
				'contrato_diaspagados' => $this->input->post('contrato_diaspagados'),
				'contrato_horaspagados' => $this->input->post('contrato_horaspagados'),
            );
            
            $contrato_id = $this->Contrato_model->add_contrato($params);
            redirect('contrato/index');
        }
        else
        {            
            $data['_view'] = 'contrato/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a contrato
     */
    function edit($contrato_id)
    {   
        // check if the contrato exists before trying to edit it
        $data['contrato'] = $this->Contrato_model->get_contrato($contrato_id);
        
        if(isset($data['contrato']['contrato_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'estado_id' => $this->input->post('estado_id'),
					'personal_id' => $this->input->post('personal_id'),
					'contrato_cargo' => $this->input->post('contrato_cargo'),
					'contrato_fechaing' => $this->input->post('contrato_fechaing'),
					'contrato_sueldo' => $this->input->post('contrato_sueldo'),
					'contrato_diaspagados' => $this->input->post('contrato_diaspagados'),
					'contrato_horaspagados' => $this->input->post('contrato_horaspagados'),
                );

                $this->Contrato_model->update_contrato($contrato_id,$params);            
                redirect('contrato/index');
            }
            else
            {
                $data['_view'] = 'contrato/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The contrato you are trying to edit does not exist.');
    } 

    /*
     * Deleting contrato
     */
    function remove($contrato_id)
    {
        $contrato = $this->Contrato_model->get_contrato($contrato_id);

        // check if the contrato exists before trying to delete it
        if(isset($contrato['contrato_id']))
        {
            $this->Contrato_model->delete_contrato($contrato_id);
            redirect('contrato/index');
        }
        else
            show_error('The contrato you are trying to delete does not exist.');
    }
    
}
