<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reserva extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Reserva_model');
        $this->load->model('Forma_pago_model');
        $this->load->model('Cliente_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        } 
    } 

    /*
     * Listing of reserva
     */
    function index()
    {
        $data['reserva'] = $this->Reserva_model->get_all_reserva();
        
        $data['_view'] = 'reserva/index';
        $this->load->view('layouts/main',$data);
    }

    function lista()
    {
        $data['reserva'] = $this->Reserva_model->get_all_reservames();
        
        $data['_view'] = 'reserva/indexlista';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new reserva
     */
    function add()
    {   
        $usuario_id = $this->session_data['usuario_id'];
       


        
        if(isset($_POST) && count($_POST) > 0)     
        { 
         $fecha =  $this->input->post('reserva_fechaingreso');
        $hora = $this->input->post('reserva_horaingreso');
        $dia = $this->Reserva_model->get_dia_reserva($fecha,$hora);
        if (isset($dia['reserva_id'])) {
             echo'<script type="text/javascript">
        alert("Este horario no esta disponible, consulte el calendario");
        </script>'; 
        $data['forma_pago'] = $this->Forma_pago_model->get_all_forma();
         $data['_view'] = 'reserva/add';
            $this->load->view('layouts/main',$data);
           
        }else{  
            $params = array(
				'reserva_tipo' => $this->input->post('reserva_tipo'),
				'cliente_id' => $this->input->post('cliente_id'),
				'usuario_id' => $usuario_id,
				'reserva_glosa' => $this->input->post('reserva_glosa'),
				'reserva_monto' => $this->input->post('reserva_monto'),
				'reserva_periodo' => $this->input->post('reserva_periodo'),
				'reserva_fechaingreso' => $this->input->post('reserva_fechaingreso'),
				'reserva_fechasalida' => $this->input->post('reserva_fechaingreso'),//misma
				'reserva_horaingreso' => $this->input->post('reserva_horaingreso'),
				'reserva_horasalida' => $this->input->post('reserva_horasalida'),
				//'reserva_fecha' => $this->input->post('reserva_fecha'),
                'forma_id' => $this->input->post('forma_id'),
            );
            
            $reserva_id = $this->Reserva_model->add_reserva($params);
            redirect('reserva/index');
        }
        }
        else
        {      
            $data['forma_pago'] = $this->Forma_pago_model->get_all_forma();      
            $data['_view'] = 'reserva/add';
            $this->load->view('layouts/main',$data);
        }
    }  
     

    /*
     * Editing a reserva
     */
    function edit($reserva_id)
    {   
        // check if the reserva exists before trying to edit it
        $data['reserva'] = $this->Reserva_model->get_reserva($reserva_id);
        $usuario_id = $this->session_data['usuario_id'];
        if(isset($data['reserva']['reserva_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'reserva_tipo' => $this->input->post('reserva_tipo'),
					'cliente_id' => $this->input->post('cliente_id'),
					'usuario_id' => $usuario_id,
					'reserva_glosa' => $this->input->post('reserva_glosa'),
					'reserva_monto' => $this->input->post('reserva_monto'),
					'reserva_periodo' => $this->input->post('reserva_periodo'),
					'reserva_fechaingreso' => $this->input->post('reserva_fechaingreso'),
					'reserva_fechasalida' => $this->input->post('reserva_fechaingreso'),//misma
					'reserva_horaingreso' => $this->input->post('reserva_horaingreso'),
					'reserva_horasalida' => $this->input->post('reserva_horasalida'),
					//'reserva_fecha' => $this->input->post('reserva_fecha'),
                    'forma_id' => $this->input->post('forma_id'),
                );

                $this->Reserva_model->update_reserva($reserva_id,$params);            
                redirect('reserva/index');
            }
            else
            {
                $data['cliente'] = $this->Cliente_model->get_cliente($data['reserva']['cliente_id']);
                $data['_view'] = 'reserva/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The reserva you are trying to edit does not exist.');
    } 

    /*
     * Deleting reserva
     */
    function remove($reserva_id)
    {
        $reserva = $this->Reserva_model->get_reserva($reserva_id);

        // check if the reserva exists before trying to delete it
        if(isset($reserva['reserva_id']))
        {
            $this->Reserva_model->delete_reserva($reserva_id);
            redirect('reserva/index');
        }
        else
            show_error('The reserva you are trying to delete does not exist.');
    }
    
}
