<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Servicio_temporal extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Servicio_temporal_model');
    } 

    /*
     * Listing of servicio_temporal
     */
    function index()
    {
        $data['servicio_temporal'] = $this->Servicio_temporal_model->get_all_servicio_temporal();
        
        $data['_view'] = 'servicio_temporal/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new servicio_temporal
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'serviciote_imagen' => $this->input->post('serviciote_imagen'),
				'estado_id' => 1,
				'serviciote_nombre' => $this->input->post('serviciote_nombre'),
				'serviciote_duracion' => $this->input->post('serviciote_duracion'),
				'serviciote_precio' => $this->input->post('serviciote_precio'),
				'serviciote_descripcion' => $this->input->post('serviciote_descripcion'),
            );
            
            $servicio_temporal_id = $this->Servicio_temporal_model->add_servicio_temporal($params);
            redirect('servicio_temporal/index');
        }
        else
        {            
            $data['_view'] = 'servicio_temporal/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a servicio_temporal
     */
    function edit($serviciote_id)
    {   
        // check if the servicio_temporal exists before trying to edit it
        $data['servicio_temporal'] = $this->Servicio_temporal_model->get_servicio_temporal($serviciote_id);
        
        if(isset($data['servicio_temporal']['serviciote_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'serviciote_imagen' => $this->input->post('serviciote_imagen'),
					'estado_id' => $this->input->post('estado_id'),
					'serviciote_nombre' => $this->input->post('serviciote_nombre'),
					'serviciote_duracion' => $this->input->post('serviciote_duracion'),
					'serviciote_precio' => $this->input->post('serviciote_precio'),
					'serviciote_descripcion' => $this->input->post('serviciote_descripcion'),
                );

                $this->Servicio_temporal_model->update_servicio_temporal($serviciote_id,$params);            
                redirect('servicio_temporal/index');
            }
            else
            {
                $this->load->model('Estado_model');
                $data['all_estado'] = $this->Estado_model->get_all_estado_activo_inactivo();
                $data['_view'] = 'servicio_temporal/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The servicio_temporal you are trying to edit does not exist.');
    } 

    /*
     * Deleting servicio_temporal
     */
    function remove($serviciote_id)
    {
        $servicio_temporal = $this->Servicio_temporal_model->get_servicio_temporal($serviciote_id);

        // check if the servicio_temporal exists before trying to delete it
        if(isset($servicio_temporal['serviciote_id']))
        {
            $this->Servicio_temporal_model->delete_servicio_temporal($serviciote_id);
            redirect('servicio_temporal/index');
        }
        else
            show_error('The servicio_temporal you are trying to delete does not exist.');
    }
    
}
