<!DOCTYPE html>
<html>
    <head>
        <?php
        $session_data = $this->session->userdata('logged_in');
        $rolusuario = $session_data['rol'];
        ?>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>BUSINESS SYS <?php if(isset($page_title)){ echo " - ".$page_title; }?> </title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Bootstrap 3.3.6 -->
        <link rel="stylesheet" href="<?php echo site_url('resources/css/bootstrap.min.css');?>">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="<?php echo site_url('resources/fonts/fontawesome-free/css/all.min.css');?>">
        <!-- Ionicons -->
        <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="<?php echo site_url('resources/css/AdminLTE.min.css');?>">
        <!-- iCheck -->
        <link rel="stylesheet" href="<?php echo site_url('resources/plugins/icheck-bootstrap/icheck-bootstrap.min.css');?>"> 
        <!-- JQVMap -->
        <link rel="stylesheet" href="<?php echo site_url('resources/plugins/jqvmap/jqvmap.min.css');?>">
     
        <!-- overlayScrollbars -->
        <link rel="stylesheet" href="<?php echo site_url('resources/plugins/overlayScrollbars/css/OverlayScrollbars.min.css');?>">
        <!-- Daterange picker -->
        <link rel="stylesheet" href="<?php echo site_url('resources/plugins/daterangepicker/daterangepicker.css');?>">
        <!-- summernote -->
        <link rel="stylesheet" href="<?php echo site_url('resources/plugins/summernote/summernote-bs4.css');?>">
        <!-- AdminLTE Skins. Choose a skin from the css/skins
             folder instead of downloading all of them to reduce the load. 
        <link rel="stylesheet" href="<?php /*echo site_url('resources/css/_all-skins.min.css');*/?>">-->

        <!-- Google Font: Source Sans Pro -->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

        <link rel="shortcut icon" href="<?php echo site_url('resources/images/icono.png');?>" />
      <!-- Font Awesome 
      <link rel="stylesheet" href="plugins/fontawesome-free/css/all.min.css">-->
      
      <!-- Tempusdominus Bbootstrap 4 
      <link rel="stylesheet" href="plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">-->
     
     
    </head>
    
    <body class="hold-transition sidebar-mini layout-fixed sidebar-collapse">
        <div class="wrapper">
                          <!-- Navbar -->
          <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
              <li class="nav-item">
                <h2>Business Sys</h2>
              </li>
            </ul>
            <!-- SEARCH FORM -->
            

          </nav>
          <!-- /.navbar -->
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="main-sidebar sidebar-dark-primary elevation-4">
                <!-- Brand Logo -->
                <a href="#" class="brand-link">
                  <img src="<?php echo site_url('resources/images/logo2.png');?>" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                       style="opacity: .8">
                  <span class="brand-text font-weight-light"><b>BUSINESS</b> SYS</span>
                </a>
                <!-- sidebar: style can be found in sidebar.less -->
                   
                <!-- /.sidebar -->
            </aside>

            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <!-- Main content -->
                <section class="content">
                    <?php                    
                    if(isset($_view) && $_view)
                        $this->load->view($_view);
                    ?>                    
                </section>
                <!-- /.content -->
            </div>
            <!-- /.content-wrapper -->
            <footer class="main-footer no-print">
                <strong>Generated By <a href="https://hvsistemasysoluciones.com/">HV Sistemas y Soluciones</a></strong>
            </footer>

            <!-- Control Sidebar -->
            <aside class="control-sidebar control-sidebar-dark">
                <!-- Create the tabs -->
                <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
                    
                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                    <!-- Home tab content -->
                    <div class="tab-pane" id="control-sidebar-home-tab">

                    </div>
                    <!-- /.tab-pane -->
                    <!-- Stats tab content -->
                    <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
                    <!-- /.tab-pane -->
                    
                </div>
            </aside>
            <!-- /.control-sidebar -->
            <!-- Add the sidebar's background. This div must be placed
            immediately after the control sidebar -->
            <div class="control-sidebar-bg"></div>
        </div>
        <!-- ./wrapper -->

        
            <!-- jQuery -->
            <script src="<?php echo site_url('resources/plugins/jquery/jquery.min.js');?>"></script>
            <!-- jQuery UI 1.11.4 -->
            <script src="<?php echo site_url('resources/plugins/jquery-ui/jquery-ui.min.js');?>"></script>
            <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
            <script>
              $.widget.bridge('uibutton', $.ui.button)
            </script>
            <!-- Bootstrap 4 -->
            <script src="<?php echo site_url('resources/plugins/bootstrap/js/bootstrap.bundle.min.js');?>"></script>
            <!-- ChartJS -->
            <script src="<?php echo site_url('resources/plugins/chart.js/Chart.min.js');?>"></script>
            <!-- Sparkline -->
            <script src="<?php echo site_url('resources/plugins/sparklines/sparkline.js');?>"></script>
            <!-- JQVMap -->
            <script src="<?php echo site_url('resources/plugins/jqvmap/jquery.vmap.min.js');?>"></script>
            <script src="<?php echo site_url('resources/plugins/jqvmap/maps/jquery.vmap.usa.js');?>"></script>
            <!-- jQuery Knob Chart -->
            <script src="<?php echo site_url('resources/plugins/jquery-knob/jquery.knob.min.js');?>"></script>
            <!-- daterangepicker -->
            <script src="<?php echo site_url('resources/plugins/moment/moment.min.js');?>"></script>
            <script src="<?php echo site_url('resources/plugins/daterangepicker/daterangepicker.js');?>"></script>
            <!-- Tempusdominus Bootstrap 4 -->
            <script src="<?php echo site_url('resources/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js');?>"></script>
            <!-- Summernote -->
            <script src="<?php echo site_url('resources/plugins/summernote/summernote-bs4.min.js');?>"></script>
            <!-- overlayScrollbars -->
            <script src="<?php echo site_url('resources/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js');?>"></script>
            <!-- AdminLTE App -->
            <script src="<?php echo site_url('resources/js/adminlte.js');?>"></script>
            <!-- AdminLTE dashboard demo (This is only for demo purposes) 
            <script src="<?php echo site_url('resources/js/pages/dashboard.js');?>"></script>-->
            <!-- AdminLTE for demo purposes -->
            <script src="<?php echo site_url('resources/js/demo.js');?>"></script>
    </body>
</html>
