<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Contrato_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get contrato by contrato_id
     */
    function get_contrato($contrato_id)
    {
        return $this->db->get_where('contrato',array('contrato_id'=>$contrato_id))->row_array();
    }
        
    /*
     * Get all contrato
     */
    function get_all_contrato()
    {
        $this->db->order_by('contrato_id', 'desc');
        return $this->db->get('contrato')->result_array();
    }
        
    /*
     * function to add new contrato
     */
    function add_contrato($params)
    {
        $this->db->insert('contrato',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update contrato
     */
    function update_contrato($contrato_id,$params)
    {
        $this->db->where('contrato_id',$contrato_id);
        return $this->db->update('contrato',$params);
    }
    
    /*
     * function to delete contrato
     */
    function delete_contrato($contrato_id)
    {
        return $this->db->delete('contrato',array('contrato_id'=>$contrato_id));
    }
}
