<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Inscripcion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get inscripcion by inscripcion_id
     */
    function get_inscripcion($inscripcion_id)
    {
         $inscripcion = $this->db->query("
        SELECT
               i.*, u.usuario_nombre, c.cliente_nombre, c.cliente_celular, s.serviciote_nombre, s.serviciote_duracion
            FROM
                inscripcion i
            LEFT JOIN usuario u on i.usuario_id=u.usuario_id
            LEFT JOIN  cliente c on i.cliente_id=c.cliente_id
            LEFT JOIN  servicio_temporal s on i.serviciote_id=s.serviciote_id
            WHERE
               i.inscripcion_id=".$inscripcion_id."
                
            ORDER BY i.inscripcion_fechaini DESC 
        "
        )->row_array();
         return $inscripcion;
    }
        
    /*
     * Get all inscripcion
     */
    function get_all_inscripcion()
    {
        $this->db->order_by('inscripcion_id', 'desc');
        return $this->db->get('inscripcion')->result_array();
    }
        
    /*
     * function to add new inscripcion
     */
    function add_inscripcion($params)
    {
        $this->db->insert('inscripcion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update inscripcion
     */
    function update_inscripcion($inscripcion_id,$params)
    {
        $this->db->where('inscripcion_id',$inscripcion_id);
        return $this->db->update('inscripcion',$params);
    }
    
    /*
     * function to delete inscripcion
     */
    function delete_inscripcion($inscripcion_id)
    {
        return $this->db->delete('inscripcion',array('inscripcion_id'=>$inscripcion_id));
    }

    function fechainscripcion($condicion,$estado)
    {

       $inscripcion = $this->db->query("
        SELECT  i.*, u.usuario_nombre, c.cliente_nombre, c.cliente_celular, s.serviciote_nombre, s.serviciote_duracion, f.forma_nombre
FROM inscripcion i
            LEFT JOIN usuario u on i.usuario_id=u.usuario_id
            LEFT JOIN  cliente c on i.cliente_id=c.cliente_id
            LEFT JOIN  servicio_temporal s on i.serviciote_id=s.serviciote_id
            LEFT JOIN  forma_pago f on i.forma_id=f.forma_id
INNER JOIN
        (
        SELECT
            
        MAX(inscripcion_fecha) as fecha, cliente_id
            FROM
                inscripcion
            WHERE
                1=1   
                ".$condicion." 
                ".$estado."
        GROUP BY cliente_id    
            
        ) AS p2
        ON i.cliente_id = p2.cliente_id
        AND i.inscripcion_fecha = p2.fecha
        WHERE 1=1
        ORDER BY i.inscripcion_fecha DESC 
        "
        )->result_array();

        return $inscripcion;
    }

    function buscar_cliente($ci)
    {

        $sql = "select * from cliente where cliente_ci = ".$ci;        
        $resultado = $this->db->query($sql)->result_array();
        
        return $resultado;
    }
}
