<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reserva_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get reserva by reserva_id
     */
    function get_reserva($reserva_id)
    {
        return $this->db->get_where('reserva',array('reserva_id'=>$reserva_id))->row_array();
    }
        
    /*
     * Get all reserva
     */
    function get_all_reserva()
    {
        $reserva = $this->db->query("
        SELECT
               r.*, u.usuario_nombre, c.cliente_nombre, c.cliente_celular, f.forma_nombre
            FROM
                reserva r
            LEFT JOIN usuario u on r.usuario_id=u.usuario_id
            LEFT JOIN  cliente c on r.cliente_id=c.cliente_id
            
            LEFT JOIN  forma_pago f on r.forma_id=f.forma_id
            WHERE
                
                date(reserva_fechasalida) >= date(now())
            ORDER BY r.reserva_id DESC 
        "
        )->result_array();

        return $reserva;
    }

    function get_all_reservames()
    {
        $reserva = $this->db->query("
        SELECT
               r.*, u.usuario_nombre, c.cliente_nombre, c.cliente_celular, f.forma_nombre
            FROM
                reserva r
            LEFT JOIN usuario u on r.usuario_id=u.usuario_id
            LEFT JOIN  cliente c on r.cliente_id=c.cliente_id
            
            LEFT JOIN  forma_pago f on r.forma_id=f.forma_id
            WHERE
                
                month(reserva_fechasalida) = month(now())
            ORDER BY r.reserva_id DESC 
        "
        )->result_array();

        return $reserva;
    }

    function get_dia_reserva($fecha,$hora)
    {
        $reserva = $this->db->query("
        SELECT
               r.reserva_id
            FROM
                reserva r
          
            WHERE
                
                r.reserva_fechaingreso = '".$fecha."'
                and r.reserva_horaingreso <= '".$hora."'
                and r.reserva_horasalida >= '".$hora."'
            ORDER BY r.reserva_id DESC 
        "
        )->row_array();

        return $reserva;
    }
        
    /*
     * function to add new reserva
     */
    function add_reserva($params)
    {
        $this->db->insert('reserva',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update reserva
     */
    function update_reserva($reserva_id,$params)
    {
        $this->db->where('reserva_id',$reserva_id);
        return $this->db->update('reserva',$params);
    }
    
    /*
     * function to delete reserva
     */
    function delete_reserva($reserva_id)
    {
        return $this->db->delete('reserva',array('reserva_id'=>$reserva_id));
    }
}
