<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Salario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get salario by salario_id
     */
    function get_salario($salario_id)
    {
        return $this->db->get_where('salario',array('salario_id'=>$salario_id))->row_array();
    }

    function get_salarioaux($salario_id)
    {
        return $this->db->get_where('salario_aux',array('salario_id'=>$salario_id))->row_array();
    }

    function get_planilla($planilla_id)
    {
        return $this->db->get_where('planilla',array('planilla_id'=>$planilla_id))->row_array();
    }

    function get_salariocontrato($salario_id)
    {
        $personal = $this->db->query("
            SELECT
                s.*, p.*

            FROM
                salario s, personal p

            WHERE
                s.salario_id = ".$salario_id." and
                s.personal_id=p.personal_id
               

        ")->row_array();

        return $personal;
    }
        
    /*
     * Get all salario
     */
    function get_all_salario()
    {
        $this->db->order_by('salario_id', 'desc');
        return $this->db->get('salario')->result_array();
    }

    function get_all_salarioplanilla($planilla_id)
    {
        $planilla = $this->db->query("
            SELECT
                s.*, p.*, c.*

            FROM
                salario s, personal p, contrato c

            WHERE
                s.planilla_id = ".$planilla_id." and
                s.personal_id=p.personal_id and
                s.contrato_id=c.contrato_id
               

        ")->result_array();

        return $planilla;
    }

    function get_planilla_aux($usuario_id)
    {
        $planilla = $this->db->query("
            SELECT
                s.*, p.*, c.*

            FROM
                salario_aux s, personal p, contrato c

            WHERE
                s.usuario_id = ".$usuario_id." and
                s.personal_id=p.personal_id and
                s.contrato_id=c.contrato_id
               

        ")->result_array();

        return $planilla;
    }
        
    /*
     * function to add new salario
     */
    function add_salario($params)
    {
        $this->db->insert('salario',$params);
        return $this->db->insert_id();
    }

    function add_planilla($params)
    {
        $this->db->insert('planilla',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update salario
     */
    function update_salario($salario_id,$params)
    {
        $this->db->where('salario_id',$salario_id);
        return $this->db->update('salario',$params);
    }
    
    /*
     * function to delete salario
     */
    function delete_salario($salario_id)
    {
        return $this->db->delete('salario',array('salario_id'=>$salario_id));
    }
}
