<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Servicio_temporal_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get servicio_temporal by serviciote_id
     */
    function get_servicio_temporal($serviciote_id)
    {
        return $this->db->get_where('servicio_temporal',array('serviciote_id'=>$serviciote_id))->row_array();
    }
        
    /*
     * Get all servicio_temporal
     */
    function get_all_servicio_temporal()
    {
        $this->db->order_by('serviciote_id', 'desc');
        return $this->db->get('servicio_temporal')->result_array();
    }
        
    /*
     * function to add new servicio_temporal
     */
    function add_servicio_temporal($params)
    {
        $this->db->insert('servicio_temporal',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update servicio_temporal
     */
    function update_servicio_temporal($serviciote_id,$params)
    {
        $this->db->where('serviciote_id',$serviciote_id);
        return $this->db->update('servicio_temporal',$params);
    }
    
    /*
     * function to delete servicio_temporal
     */
    function delete_servicio_temporal($serviciote_id)
    {
        return $this->db->delete('servicio_temporal',array('serviciote_id'=>$serviciote_id));
    }
}
